kind: Service
apiVersion: v1
metadata:
  name: prometheus
  labels:
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
